### PR TITLE
Fix UnusedDungeonChance crash

### PR DESCRIPTION
**Pull request by End45**
Fixes a crash introduced in UnusedDungeonChance v0.1.1 that could happen when generating a wall maze room.

### CODE REVIEW

**Comment by theCapypara** [comment]
@End45 Thanks! Please rebase your changes on `version/1.5.x`. I was going to do it, but then I saw it's the master branch of your fork, so that's probably not a good idea. You may need to re-open the PR if you want to use another branch.

**Comment by theCapypara** [comment]
Also I see in the source, that this needs the ExtraSpace patch now? In that case you need to mark it as dependant on that.

**Comment by End45** [comment]
> @End45 Thanks! Please rebase your changes on `version/1.5.x`. I was going to do it, but then I saw it's the master branch of your fork, so that's probably not a good idea. You may need to re-open the PR if you want to use another branch.

Did it on master because I expected it was going to be an easy merge. Should have done it properly lol. I'll fix it.

> Also I see in the source, that this needs the ExtraSpace patch now? In that case you need to mark it as dependant on that.

Oops, right. I was going to do it and forgot. Thanks.

**Comment by theCapypara** [comment]
@End45 Can you make sure the type checks run through? At least one of them will probably actually cause runtime issues.

**Comment by End45** [comment]
Right, forgot about the imports

**Pull request merged**
