### PR TITLE
Appraise all boxes at once patch

### PR DESCRIPTION
**Pull request by irdkwia**
Adds a patch enabling a new option to appraise all boxes at once from Xatu's box appraisal menu (NA/EU versions).
Example of how it works: https://youtu.be/Lrs26tPNwU4

Thanks to @Adex-8x for testing it!

### CODE REVIEW

**Comment by theCapypara** [comment]
Cool, thanks! I wonder why the Github checks don't run, I'll check that later.

**Review by theCapypara — APPROVED** [review]

**Review by theCapypara — CHANGES_REQUESTED** [review]
It seems you are somehow still banned from triggering Github Actions, but running the checks locally, I get some errors from mypy, could you fix them?:

` black -t py38 --extend-exclude _resources/pmdsky-debug skytemple_files && pycln skytemple_files -a && mypy skytemple_files`

```black -t py38 --extend-exclude _resources/pmdsky-debug skytemple_files && pycln skytemple_files -a && mypy skytemple_files
All done! ✨ 🍰 ✨
563 files left unchanged.
Looks good! ✨ 🍰 ✨
563 files left unchanged.
skytemple_files/patch/handler/appraise_all.py:138: error: Unsupported operand types for - ("str" and "int")
skytemple_files/patch/handler/appraise_all.py:138: note: Left operand is of type "Union[int, str]"
skytemple_files/patch/handler/appraise_all.py:141: error: Unsupported operand types for - ("str" and "int")
skytemple_files/patch/handler/appraise_all.py:141: note: Left operand is of type "Union[int, str]"
skytemple_files/patch/handler/appraise_all.py:146: error: Unsupported operand types for - ("str" and "int")
skytemple_files/patch/handler/appraise_all.py:146: note: Left operand is of type "Union[int, str]"
skytemple_files/patch/handler/appraise_all.py:151: error: Unsupported operand types for - ("str" and "int")
skytemple_files/patch/handler/appraise_all.py:151: note: Left operand is of type "Union[int, str]"
Found 4 errors in 1 file (checked 563 source files)
```

**Comment by irdkwia** [comment]
It should work now

**Review by theCapypara — APPROVED** [review]
Thanks!

**Pull request merged**
