### PR TITLE
Consolidate string blocks across NA/EU/JP versions

### PR DESCRIPTION
**Pull request by in2erval**
This PR aims to revise the string blocks that are currently defined for the three Explorers of Sky versions (NA/EU/JP). The text linking was done via spreadsheet and added to the directory for future reference as `linked-eos-strs.csv`.

This new set of blocks have been compared with the previous version to ensure the regions being used by the UI (https://github.com/SkyTemple/skytemple/blob/e90441e56af1e0523254efe3498161b8981ac771/skytemple/core/string_provider.py#L32-L59) are named the same - there are some changes which I believe should be applied however:

### NA
* IQ Skills Names: **(9957, 10025) -> (9956, 10025)** 
  * ID 9957 should be included as the equivalent JP string is "[M:D1]かしこさ なし" meaning "No IQ"
* Trap Names: **(13504, 13530) -> (13504, 13529)** 
  * ID 13530 should not be included as it's a Trap Description

### EU
* IQ Skills Names: **(9959, 10027) -> (9958, 10027)** 
  * Same reason as NA

### JP
* IQ Skills Names: **(16147, 16216) -> (16146, 16215)** 
  * Same reason as NA, but also ID 16216 should not be included as it's an IQ Skills Description
* Move Descriptions: **(16286, 16844) -> (16286, 16845)** 
  * ID 16845 should be included as it's included in other versions - NA 10704, EU 10706
* Item Long Descriptions: **(16844, 18245) -> (16845, 18245)** 
  * ID 16845 should not be included as it's a Move Description

### CODE REVIEW

**Comment by theCapypara** [comment]
Thanks! If we change existing strings then this is a breaking change but its probably worth it. Thanks for documenting it!

I'll review and test this today or tomorrow and then merge. Can you also open a new PR for the Randomizer for your smart text replacements to use the new string regions?

**Comment by theCapypara** [comment]
@End45 Since this is quite the substential change I also added you as reviewer. Could you also have a look & check if any patch would break?

**Comment by in2erval** [comment]
> I'll review and test this today or tomorrow and then merge. Can you also open a new PR for the Randomizer for your smart text replacements to use the new string regions?

Yep, I can get that PR going as well.

**Comment by in2erval** [comment]
> I don't get this. String #9959 is the empty string before IQ skill names, which is already included and makes sense to include since, as you said, it represents "No IQ skill". But 9958 is "The Pokémon becomes afflicted with a\n[LS:13756]Terrified[LE] status. It will flee from\nenemies and friends, and it can't use\nitems while fleeing.\n\n\n\n\nSelect detail:[CLUM_SET:70][M:B4] or [M:B5]/View detail: [M:B2]\0". Are you sure those numbers are right?

The way that `beg` and `end` works in the XML seems to be that it selects strings based on `beg < string_id <= end` - 9958 is not actually part of IQ Skills Names:

image

This is likely due to the fact that string_id being indexed from 1 instead of 0 - let me know if this interpretation is incorrect.

**Comment by theCapypara** [comment]
That is correct, the string IDs in SkyTemple are 1-indexed since the game also uses 1-indexing (effectively).

**Comment by theCapypara** [comment]
> @End45 How would this break patches exactly?

I thought there were some patches that used strings, but maybe not.

**Comment by End45** [comment]
> The way that beg and end works in the XML seems to be that it selects strings based on beg < string_id <= end

Huh. That doesn't make much sense (even if the strings are 1-indexed), but I see. The numbers are correct then.

> I thought there were some patches that used strings, but maybe not.

Some ASM patches might directly load strings by their ID, but those are not affected by changes to how SkyTemple groups them. So I think it should be alright.

**Review by theCapypara — APPROVED** [review]
LGTM! Thanks again!

**Review by End45 — APPROVED** [review]

**Pull request merged**
