### PR TITLE
More updates to parameters from wiki

### PR DESCRIPTION
**Pull request by Chesyon**
All of the parameters here should now be fully consistent with https://wiki.skytemple.org/index.php/List_of_Opcodes

### CODE REVIEW

**Comment by theCapypara** [comment]
Hi, your changes cause some issues with decompiling/compiling scripts from the game. Please check those. If you need any help, let me know.

**Comment by theCapypara** [comment]
@Chesyon Particularly "Addr" is not a valid argument type.

**Comment by Chesyon** [comment]
Sorry about that! It should hopefully be fixed now. I'll update the wiki accordingly, once the checks finish, assuming that everything works properly this time.

**Comment by theCapypara** [comment]
For the wiki Addr is probably fine. Any opcode with a jump to an adress isn't really used anyway since all of them have language syntax.

**Comment by theCapypara** [comment]
Thanks!

**Pull request merged**
