### PR TITLE
Japanese compatibility for most ASM Patches + Patch Updates

### PR DESCRIPTION
**Pull request by Adex-8x**
Adds Japanese ROM compatibility for most ASM Patches! Should close https://github.com/SkyTemple/skytemple-files/issues/405.
Additionally, various ASM Patches have received updates:

- `AddTypes` now has a patch parameter to determine the Conversion 2 type matchup against Fairy.
- `AddTypes` has a "bugfix" that reverts the "Normal -> Ghost" and "Fighting -> Ghost" matchups to be effective instead of immune. This is actually how it is in the base game, for some reason.
- `CompleteTeamControl` now uses Text Strings instead of an ASCII string baked into the patch, to allow for translations.
- `PitfallTrapTweak` now hides the UI when going back a floor.

As of now, the following patches do not yet have JP ROM compatibility:

- `ChangeMoveStatsDisplay`: Crashes when attempting to view a move's description in ground and dungeon mode. This also seems to softlock in the EU version as well, so it may be an underlying issue with the patch in general.
   - See the "TODO STAT_DISP:" comments for areas of concern.
- `ExpandPokeList`: Untested due to an unknown issue (SkyTemple hangs indefinitely)! I have various concerns with this patch in regards to dungeon mode, so having others take a look at this is strongly encouraged! ~~I'm suffering so much with this one please help someone anyone~~
   - See the "TODO EXPAND_POKE_LIST:" comments for areas of concern.
- `ExternalizeMappaFile`: While this patch does not crash on hardware, it seems to read certain attributes incorrectly. For example, trying to place Pitfall Traps in a dungeon after applying this patch actually placed Chestnut Traps.
- `MoveGrowth`: Relies on `ChangeMoveStatsDisplay`.

I apologize for not fully supporting them in this PR, but I at least wanted to add what I have so far, and get other opinions (be it now or in the future) as to what may be causing these last few issues.

Additionally, I would suggest that @Laioxy take a look at `fairy_gummies.py` to see if the Japanese translation of the Fairy Gummi is accurate.

Testing of all of these patches on a platform that _isn't_ DeSmuME is strongly encouraged, as although I have tested them myself, there's always a chance I missed something.

### CODE REVIEW

**Comment by Laioxy** [comment]
I have checked the Japanese translation of Fairy Gummi. Rather than using the type name "Fairy" as it is, I think it would be more appropriate to use a color name that evokes the appearance and type.
For example, "うすももグミ"(Usumomo Gumi). It means light pink.
I really wanted to name it "ももいろグミ" but gave up because it is already used for poison type gummies.

**Comment by Adex-8x** [comment]
Ah I see, thank you for checking it!
Maybe a name like "うすももグミ" would be more fitting, yeah. We'll see what Para thinks as well
My only worry is that it wouldn’t be consistent with other languages’ translations

**Comment by theCapypara** [comment]
First, thank you a lot! I'll check everything later. 

How is that translation wrong with the other language translations? Aren't gummies always named after color? If the Fairy Gummi is currently called that in the other languages then that's probably wrong.

**Comment by Adex-8x** [comment]
Gummies are usually named after their color, yeah, but the [current translations](https://github.com/SkyTemple/skytemple-files/blob/fd26f876f48e42b69f08702e726669c36ea7826c/skytemple_files/patch/handler/fairy_gummies.py#L55-L59) opt to literally go for "Fairy Gummi".

**Comment by theCapypara** [comment]
This PR also includes https://github.com/PsyCommando/pmd2_asm_mods/pull/5

**Review by theCapypara — APPROVED** [review]
LGTM. I haven't tested all patches but generally this seems good. If okay for everyone I would merge.

**Comment by Adex-8x** [comment]
All fine with me! Whenever I’ve got more time I’ll be able to look into the last four patches that are giving us trouble.

**Comment by Laioxy** [comment]
You may disregard my comments regarding translation! I was talking about something like naming conventions 💦
If a name like "Fairy Gummi" has already been established, then that is fine. By the way, the Japanese translation of "フェアリーグミ"(Fairy Gummi) itself is correct.

**Comment by theCapypara** [comment]
I mean personally I still think we should maybe change it for all languages to be a color. But maybe that can be an extra Pull Request.

**Pull request merged**
